"""empty message

Revision ID: f87ed4634a9a
Revises: 8c688724c2c8
Create Date: 2020-10-24 23:17:28.039543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87ed4634a9a'
down_revision = '8c688724c2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('artist', 'seekin_description')
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('venue', 'seekin_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seekin_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_description')
    op.add_column('artist', sa.Column('seekin_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
